#!/usr/bin/awk -f

#This program parses dictionary.txt to make a [String] dictionary to use in the game
BEGIN {
  counter=0
  printf "module Dictionary where\n\n";
  printf "dictionary = ["
}
{
  printf "%s\"%s\"", com, $1;
  com=","
  counter++
}
END {
 print "] :: [String]"
 printf "\nlen = %d :: Int", counter;
}
